config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :products
  resources :users
  resources :categories

  root to: 'home#index'
end

app/models/admin.rb
class Admin < User
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
	belongs_to :category

	serialize :description, Array
end

app/models/category.rb
class Category < ApplicationRecord
	has_many :products
	has_many :users, :through  => :products
end

app/models/product.rb
class Product < ApplicationRecord
	belongs_to :user
	belongs_to :category

	serialize :description, Array
	
	# user & category ID are both required through the belongs_to association
	# Description is an array and optional, with a 100 max chars per array item (which will be a line in a list item)
	
	validates :name, presence:true, length: {minimum: 3, maximum: 240}
  validates :description, length: {minimum: 5, maximum: 50}
  validates :price, numericality: { greater_than_or_equal_to: 10, less_than_or_equal_to: 5000 }
  validates :summary, presence:true, length: {minimum: 4, maximum: 500}
  default_scope -> { order(updated_at: :desc) }

end

app/models/seller.rb
class Seller < User
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :confirmable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :products
	has_many :categories, :through  => :products

	def full_name
    "#{first_name} #{last_name}" 
	end

	mount_uploader :image, UserImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
    
    before_action :set_category, only: [:edit, :update, :show, :destroy]

  def new
    @category = Category.new
  end
  
  def create
    @category = Category.new(category_params)
    if @category.save
      redirect_to category_path(@category)
    else
      render 'new'
    end
  end
  
  def edit
  end

  def update
    if @category.update(category_params)
      flash[:success] = "Category successfully updated"
      redirect_to category_path(@category)
    else
      render 'edit'
    end
  end

  def show
    #@category_products = @category.products
  end
  
  def index
    #@categories = Category.paginate(page: params[:page], per_page: 5)
    @categories = Category.all
  end
  
  def destroy
    @category.destroy
    #flash[:success] = "Goal successfully deleted!"
    redirect_to categories_path
  end

  private

  def set_category
    @category = Category.find(params[:id])  
  end
  
  def category_params
    params.require(:category).permit(:name)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  before_action :set_product, only: [:show, :edit, :update, :destroy] 

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def create
    @product = Product.new(product_params)
    @product.user = current_user
    @product.description.split(',')
    if @product.save
      flash[:success] = "Product has been added to the catalogue"
      redirect_to products_path
    else
      flash[:warning] = "Product has not been added to the catalogue"
      render 'new'
    end
  end

  def edit
  end

  def update
    @product.description.split(',')
    if @product.update(product_params)
      flash[:success] = "Product has been updated"
      redirect_to products_path
    else
      render 'edit'
    end
  end

  def show
  end

  def destroy
    @product.destroy
    flash[:danger] = "product has been removed from the catalogue"
    redirect_to products_path
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end
    def product_params
      params.require(:product).permit(:category_id, :name, :price, :summary, description: [])
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@users = User.all
	end

	def show
		@user = User.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/categories/_form.html.erb
<div class="row">
  <div class="col-md-12">
    <%= form_for(@category, :html => {class: "form-horizontal", role: "form"}) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
          <%= f.label :name %>
        </div>
        <div class="col-md-8">
          <%= f.text_field :name, class: "form-control", placeholder: "Name of category",  autofocus: true %>
        </div>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit(@category.new_record? ? "Add Category" : "Edit Category",
                                                class: "btn btn-primary btn-lg btn-xlarge") %>
        </div>
      </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to Categories",  categories_path %> ]
    </div>
  </div>
</div>

app/views/categories/edit.html.erb
<br>
<H1>Edit a Category</H1>

<%= render 'form' %>

app/views/categories/index.html.erb
<center><h1> Explore by Category </h1></center>
<% @categories.each do |cat| %>
  <div class="wellc">
    <div class="wrapper">
      <div class="box a"><%= link_to(image_tag("http://www.livecircular.com/wp-content/uploads/2016/10/other-electronic-reviews.jpg"), category_path(cat)) %></div>
      <div class="box b"><h2><%= cat.name.capitalize %> </h2> <br>
      
      <%if cat.products.any?%>
        <b>Sellers who have items in this category:</b> <br> <br>
        <ul>
          <% cat.products.each do |prod| %>
              <li><%= link_to prod.user.first_name, user_path(prod) %></li>
          <% end %>
        </ul>
      <% else %>
      <p> There are no products in this category yet!</p>
      <% end %>
        
      </div>
      <div class="box c"><%= link_to "Browse category", category_path(cat) %></div>
      <div class="box d"><p>Products in this category: <%= cat.products.count %></div>
      <div class="box e">Admin only: <%= link_to "Edit Category", edit_category_path(cat)  %> / <%= link_to "Delete", category_path(cat), method: :delete,
            data: { confirm: "Are you sure you want to delete this catgory?" }  %></p></div>
    </div>
  </div> 

<% end %>

app/views/categories/new.html.erb
<br>
<H1>Add a new Category</H1>

<%= render 'form' %>

app/views/categories/show.html.erb
<center>
<h1> <%= @category.name %></h1>
</center>

<% if @category.products.any? %>
<div class="wellc">
  <i><center>  <%= @category.products.count %> products found in <%= @category.name.capitalize %></center>
 </i><br>
      <% @category.products.each do |p| %>
        <div class="wrapper">
        <div class="box a"><%= link_to(image_tag("http://www.livecircular.com/wp-content/uploads/2016/10/other-electronic-reviews.jpg"), product_path(p)) %></div>
  
        <div class="box b">  <h3><%= p.name.capitalize %> </h3><br>
        <p><b>Product summary:</b> <%= p.summary %> <br></p>
        <% if p.description.any? %> <br>
        <b>List from the description array:</b>
          <ul>
            <% p.description.each do |desc| %> 
                <li><%= desc %></li>
            <% end %>
          </ul>

        <% end %> <br>
        <b>Sold by: </b><%= p.user.first_name %>  <%= p.user.last_name %> <br> <%= p.user.phone %>  |  <%= p.user.email %>  <br>
</div>
        
        <div class="box c"><p><%= link_to "More from seller", user_path(p), class: "btn-actions cat-button-box-c" %></p></div>
        <div class="box d"><b><p>Price: £</b> <%= p.price %></div></p>
        <div class="box e"><%= link_to "Edit Product", edit_product_path(p), class: "btn-actions cat-button"  %> <%= link_to "Delete", product_path(p), method: :delete,
              data: { confirm: "Are you sure you want to delete this product?" }, class: "btn-actions cat-button"  %></p></div>
        </div>
        <br>
     <% end %>
  <% else %>
    <h4 align="center"> There are no products in the <%= @category.name.capitalize %> category yet! </h4>
  <% end %>
  </div>
</div>

app/views/home/index.html.erb
<header>
	<div class="text-box">
		<h1>Sunday Market!</h1>
		<%= link_to "More Information", "", class: "btn btn-full" %>
		<%= link_to "Testimonies", "", class: "btn btn-ghost" %>
	</div>
</header>

<section class="section about-market">
	<div class="container">
		<div class="row">
			<div class="col span-3-of-3">
				<h1>What Is Sunday Market!?</h1>
				<span>
					Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............Sunday market is a place when you can...............
				</span>
			</div>
		</div>
	</div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Challenge</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render "shared/navigation" %>
     <p class="notice"> <%= notice %></p>
     <p class="alert"> <%= alert %></p>
    <section>
      <%= render  "shared/alert" %>
      <%= yield %>
    </section>
  </body>
</html>

app/views/products/_form.html.erb
<%= render "shared/error", obj: @product %>
<div class="row">
  <div class="col-xs-12">
    <%= form_for(@product, :html => {class: "form-horizontal", role: "form"}) do |f| %>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :name %>  
      </div>
      <div class="col-sm-8">
        <%= f.text_field :name, class: "form-control", placeholder: "name", autofocus: true %>
      </div>    
    </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :price %>
      </div>
      <div class="col-sm-8">
        <%= f.number_field :price, step: 0.01, class: "form-control", rows: 6, placeholder: "Price"%>
      </div>
    </div>
    <div class="form-group">
        <div class="control-label col-sm-2">
          <%= f.label :summary %>  
        </div>
        <div class="col-sm-8">
          <%= f.text_field :summary, class: "form-control", placeholder: "Product's summary", autofocus: true %>
        </div>    
      </div>
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :description %>
      </div>
      <% 5.times do %>
        <div class="col-sm-8">
            <%= f.text_field :description, multiple: true, class: "form-control", rows: 6, placeholder: "Description"%>
        </div>
      <% end %>
    </div>    
    <div class="form-group">
      <div class="row">
        <div class="col-sm-offset-2 col-sm-8">
          <%= f.collection_select :category_id, Category.order(:name),:id,:name, include_blank: true %>
        </div>
      </div>
    </div>
    <div class="form-group">
      <div class='col-md-offset-1 col-md-11'>
        <%= f.submit class: 'btn pull-right' %> 
      </div>        
    </div>
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      <%= link_to 'Cancel', root_path, class:"btn" %>
    </div>
  </div>
</div>

app/views/products/edit.html.erb
<h1>Edit product</h1>
<%= render 'form' %>

app/views/products/index.html.erb
<center><h1>Product catalogue</h1></center>

<% @products.each do |product| %>
  <div class = "wellc">
    <div class="wrapper">
      <div class="box a"><%= link_to(image_tag("http://www.livecircular.com/wp-content/uploads/2016/10/other-electronic-reviews.jpg"),
                                     product_path(product)) %></div>  
      <div class="box b">
        <h3><%= link_to product.name, product_path(product) %> </h3><br>
        Description:
        <% if product.description.any? %>
          <ul>
            <% product.description.each do |desc| %> 
              <% if desc != "" %>  
                <li><%= desc %></li>
              <% end %>
            <% end %>
          </ul>
        <% end %>
        <div class ="box c"><br> Category: <%= link_to product.category.name, category_path(product.category) %></div>
        <div class ="box d">Sold by: <%= product.user.first_name %>  <%= product.user.last_name %></div>
        <div class ="box e">
          <% if current_user == product.user %>
            <%= link_to "Edit", edit_product_path(product), class: "btn"%>
            <%= link_to "Delete",product_path(product), method: :delete,
                                data: { confirm: "Are you sure about that?"} %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/products/new.html.erb
<h3>Add an product to the catalogue</h3>
<%= render 'form' %>

app/views/products/show.html.erb
<div class="wellc">
  <div class ="wrapper">
    <div class="box a">
      <%= image_tag("http://www.livecircular.com/wp-content/uploads/2016/10/other-electronic-reviews.jpg")%>
    </div>
    <div class="box b">
      <h3> <%= @product.name %> </h3><br>
      <br>
      <b>Summary</b></br>
      <%= @product.summary %>
      </br>
      <b>Caracteristics:</b>
      <ul>
        <% @product.description.each do |description| %>
          <% if description != "" %>
            <li> <%= description %> <li>
          <% end %>
        <% end %>
      </ul>
    </div>
    <div class="box c">
      <b>Sold by: <%= @product.user.first_name %></b>
    </div>
    <div class="box d">
      Price:<%= number_to_currency(@product.price, unit: "U$") %>
    </div>
    <div>Category: <%= @product.category.name%></div>
    <div class="box e">
      <% if current_user == @product.user %>
        <%= link_to "Edit", edit_product_path(@product)%>
        <%= link_to "Delete",product_path(@product), method: :delete,
                            data: { confirm: "Are you sure about that?"} %>
      <% end %>
    </div>
  </div>
</div>

app/views/products/update.html.erb
<h1>Products#update</h1>
<p>Find me in app/views/products/update.html.erb</p>

app/views/shared/_alert.html.erb
<div class="row">
  <% flash.each do |name, msg|%>
    <div class='alert alert-<%="#{name}"%>'>
      <a href="#" class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
  <% end %>
</div>

app/views/shared/_error.html.erb
<% if obj.errors.any? %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count, "erro")%> prevented the operation.
          </h2>
        <div class="panel-body">
           <ul>
              <% obj.errors.full_messages.each do |msg|%>
                <li><%= msg %></li>
              <% end %>
          </ul>
        </div>
      </div>
    </div>
  </div>
</div>
<% end %>

app/views/shared/_navigation.html.erb
<nav>
  <div class="row">
    <%= link_to "Brand Name", root_path %>
    <ul class="main-nav">
      <li><%= link_to "Sellers", users_path %></li>
      <li><%= link_to "Categories", categories_path%></li>
      <% if signed_in? %>
      <ul>
      	<li><%= link_to current_user.full_name, user_path(current_user), id: "number_#{current_user.id}_user" %></li>
        <!--TODO: add the caret for display all this list items in a block-->
      	<li><%= link_to "Check products", products_path %></li>
      	<li><%= link_to "Add a product", new_product_path %></li>
      	<li><%= link_to "New category"%></li>
      	<li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      </ul>
      <% else %>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shared/_products.html.erb
<% obj.each do |product| %>
<div class = "row">
   <div class="col-md-8 well"> <br>
    <h4>product Name: <%= link_to product.name, product_path(product) %></h4><br>
    <h4>product Description:<%= truncate(product.description, length: 100) %></h4><br>
    <% if product.categories.any? %>
    <p> Categories: <%= render product.categories %> </p>
    <% end %>
    
    <p> <span class="quiet"> <small>Created: <%= time_ago_in_words(product.created_at) %> ago by: 
    <%= link_to  product.user.username.capitalize, user_path(product.user) %> | <%= pluralize(product.comments.count, 'Comment') %></span></p></small> <hr>
    <% if logged_in? && current_user == product.user || current_user && current_user.admin?  %>
          <%= link_to "Edit this product", edit_product_path(product), class: "btn btn-xs btn-default" %>
          <%= link_to "Delete this product", product_path(product), method: :delete,
          data: { confirm: "Are you sure you want to delete this product?" }, class: "btn btn-xs btn-danger" %> 
     <% end %>   
  </div>
</div><!-- end row -->
<% end %>

app/views/users/index.html.erb
<section class="index-users">
	<% @users.each do |user| %>
		<div class="row">
			<div class="col span-1-of-3">
				<div class="user-info-index">
					<%= image_tag(user.image, size: "100x200", class: "user-image-index")%>
					<br>
					<span class="full-name-user-index"><%= link_to user.full_name, user_path(user) %></span>
					<br />
					<span class="type-of-user"><%= user.type %></span>
					<br />
					<span class="user-index-description">
						This user has <%= user.products.count %> products & he is present in <%= user.categories.count %> categories.
					</span>
					<br />
					<div class="actions-index">
						<%= link_to "Products", "", class: "btn-actions" %>
						<%= link_to "Categories", "", class: "btn-actions" %>
					</div>
				</div>
			</div>
		</div>
	<% end %>
</section>

app/views/users/show.html.erb
<section class="show-user">
	<div class="row">
		<div class="col span-1-of-3">
			<div class="image-container">
				<%= image_tag(@user.image, size: "300x300", alt: "user_image" ) %>
				<% if current_user || current_user.try(:type) == "AdminUser" %>
					<%= link_to "Edit User", "", class: "btn-actions edit-user-button", id: "edit_#{@user.id}_user"%>
				<% end %>
			</div>
		</div>

		<div class="col span-2-of-3">
			<div class="user-information">
				<span class="hi-box">Hi</span> 
				<span class="im-user">I'm</span>
				<span class="full-name-user"> <%= @user.full_name %></span> <br>
				<span class="type-of-user"><%= @user.type %> User Of The Market!</span>
				<hr />
				<span class="email-of-user">Email: <%= @user.email %></span><br>
				<span class="phone-of-user">Phone: <%= @user.phone %></span><br>
				<span class="products-of-user">Number of products to sell: <%= @user.products.count %></span><br>
				<div class="actions">
					<%= link_to "Products to sell", "", class: "btn-actions" %>
					<%= link_to "Categories present", "", class: "btn-actions" %>
				</div>
			</div>
		</div>
	</div>
</section>